name: groupprojfinal
description: A Flutter project for managing car dealerships

publish_to: 'none' # Set to none because you’re not publishing it

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  shared_preferences: ^2.0.11
  path_provider: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


